"""Router-name location hints for TNT's traceroute. Facts only: 'this code, as used in public router host names,
refers to this place'. Written for TNT from public observations; not copied from iconectiv (CLLI), CAIDA or any
licensed dictionary. Coordinates are approximate city centres (±25 km), used only for the speed-of-light check.

Plain literals read by :mod:`tnt.geohints`; nothing is read from disk at import. Only codes seen in a public router
name are listed: a row is added only together with such an observation.
"""
from __future__ import annotations

from typing import Dict, FrozenSet, Tuple

__all__ = ["METROS", "IATA", "CLLI", "CITY", "FACILITY", "OVERRIDES", "RULES", "CC_TOKENS", "US_STATES", "STOP",
           "COUNTRY_NAMES"]

# metro key -> (city, region, ISO country code, lat, lon); region is the US state or Canadian province,
# "" when none
METROS: Dict[str, Tuple[str, str, str, float, float]] = {
    "newyork-ny": ("New York", "NY", "US", 40.71, -74.01),
    "newark-nj": ("Newark", "NJ", "US", 40.74, -74.17),
    "secaucus-nj": ("Secaucus", "NJ", "US", 40.79, -74.06),
    "losangeles-ca": ("Los Angeles", "CA", "US", 34.05, -118.24),
    "longbeach-ca": ("Long Beach", "CA", "US", 33.77, -118.19),
    "santaana-ca": ("Santa Ana", "CA", "US", 33.75, -117.87),
    "irvine-ca": ("Irvine", "CA", "US", 33.68, -117.83),
    "anaheim-ca": ("Anaheim", "CA", "US", 33.84, -117.91),
    "tustin-ca": ("Tustin", "CA", "US", 33.75, -117.83),
    "burbank-ca": ("Burbank", "CA", "US", 34.18, -118.31),
    "ontario-ca": ("Ontario", "CA", "US", 34.06, -117.65),
    "riverside-ca": ("Riverside", "CA", "US", 33.95, -117.40),
    "chicago-il": ("Chicago", "IL", "US", 41.88, -87.63),
    "dallas-tx": ("Dallas", "TX", "US", 32.78, -96.80),
    "fortworth-tx": ("Fort Worth", "TX", "US", 32.76, -97.33),
    "richardson-tx": ("Richardson", "TX", "US", 32.95, -96.73),
    "plano-tx": ("Plano", "TX", "US", 33.02, -96.70),
    "irving-tx": ("Irving", "TX", "US", 32.81, -96.95),
    "houston-tx": ("Houston", "TX", "US", 29.76, -95.37),
    "washington-dc": ("Washington", "DC", "US", 38.91, -77.04),
    "ashburn-va": ("Ashburn", "VA", "US", 39.04, -77.49),
    "reston-va": ("Reston", "VA", "US", 38.96, -77.36),
    "herndon-va": ("Herndon", "VA", "US", 38.97, -77.39),
    "mclean-va": ("McLean", "VA", "US", 38.93, -77.18),
    "philadelphia-pa": ("Philadelphia", "PA", "US", 39.95, -75.17),
    "miami-fl": ("Miami", "FL", "US", 25.76, -80.19),
    "fortlauderdale-fl": ("Fort Lauderdale", "FL", "US", 26.12, -80.14),
    "westpalmbeach-fl": ("West Palm Beach", "FL", "US", 26.72, -80.05),
    "atlanta-ga": ("Atlanta", "GA", "US", 33.75, -84.39),
    "boston-ma": ("Boston", "MA", "US", 42.36, -71.06),
    "phoenix-az": ("Phoenix", "AZ", "US", 33.45, -112.07),
    "sanfrancisco-ca": ("San Francisco", "CA", "US", 37.77, -122.42),
    "oakland-ca": ("Oakland", "CA", "US", 37.80, -122.27),
    "sanjose-ca": ("San Jose", "CA", "US", 37.34, -121.89),
    "santaclara-ca": ("Santa Clara", "CA", "US", 37.35, -121.96),
    "sunnyvale-ca": ("Sunnyvale", "CA", "US", 37.37, -122.04),
    "paloalto-ca": ("Palo Alto", "CA", "US", 37.44, -122.14),
    "fremont-ca": ("Fremont", "CA", "US", 37.55, -121.99),
    "detroit-mi": ("Detroit", "MI", "US", 42.33, -83.05),
    "seattle-wa": ("Seattle", "WA", "US", 47.61, -122.33),
    "tacoma-wa": ("Tacoma", "WA", "US", 47.25, -122.44),
    "minneapolis-mn": ("Minneapolis", "MN", "US", 44.98, -93.27),
    "sandiego-ca": ("San Diego", "CA", "US", 32.72, -117.16),
    "tampa-fl": ("Tampa", "FL", "US", 27.95, -82.46),
    "denver-co": ("Denver", "CO", "US", 39.74, -104.99),
    "stlouis-mo": ("St. Louis", "MO", "US", 38.63, -90.20),
    "baltimore-md": ("Baltimore", "MD", "US", 39.29, -76.61),
    "orlando-fl": ("Orlando", "FL", "US", 28.54, -81.38),
    "charlotte-nc": ("Charlotte", "NC", "US", 35.23, -80.84),
    "sanantonio-tx": ("San Antonio", "TX", "US", 29.42, -98.49),
    "portland-or": ("Portland", "OR", "US", 45.52, -122.68),
    "sacramento-ca": ("Sacramento", "CA", "US", 38.58, -121.49),
    "pittsburgh-pa": ("Pittsburgh", "PA", "US", 40.44, -80.00),
    "austin-tx": ("Austin", "TX", "US", 30.27, -97.74),
    "lasvegas-nv": ("Las Vegas", "NV", "US", 36.17, -115.14),
    "cincinnati-oh": ("Cincinnati", "OH", "US", 39.10, -84.51),
    "columbus-oh": ("Columbus", "OH", "US", 39.96, -83.00),
    "indianapolis-in": ("Indianapolis", "IN", "US", 39.77, -86.16),
    "cleveland-oh": ("Cleveland", "OH", "US", 41.50, -81.69),
    "nashville-tn": ("Nashville", "TN", "US", 36.16, -86.78),
    "norfolk-va": ("Norfolk", "VA", "US", 36.85, -76.29),
    "newportnews-va": ("Newport News", "VA", "US", 37.09, -76.47),
    "providence-ri": ("Providence", "RI", "US", 41.82, -71.41),
    "jacksonville-fl": ("Jacksonville", "FL", "US", 30.33, -81.66),
    "milwaukee-wi": ("Milwaukee", "WI", "US", 43.04, -87.91),
    "raleigh-nc": ("Raleigh", "NC", "US", 35.78, -78.64),
    "durham-nc": ("Durham", "NC", "US", 35.99, -78.90),
    "oklahomacity-ok": ("Oklahoma City", "OK", "US", 35.47, -97.52),
    "memphis-tn": ("Memphis", "TN", "US", 35.15, -90.05),
    "richmond-va": ("Richmond", "VA", "US", 37.54, -77.44),
    "louisville-ky": ("Louisville", "KY", "US", 38.25, -85.76),
    "neworleans-la": ("New Orleans", "LA", "US", 29.95, -90.07),
    "saltlakecity-ut": ("Salt Lake City", "UT", "US", 40.76, -111.89),
    "hartford-ct": ("Hartford", "CT", "US", 41.76, -72.68),
    "newhaven-ct": ("New Haven", "CT", "US", 41.31, -72.92),
    "buffalo-ny": ("Buffalo", "NY", "US", 42.89, -78.88),
    "birmingham-al": ("Birmingham", "AL", "US", 33.52, -86.80),
    "rochester-ny": ("Rochester", "NY", "US", 43.16, -77.61),
    "grandrapids-mi": ("Grand Rapids", "MI", "US", 42.96, -85.67),
    "tucson-az": ("Tucson", "AZ", "US", 32.22, -110.97),
    "honolulu-hi": ("Honolulu", "HI", "US", 21.31, -157.86),
    "tulsa-ok": ("Tulsa", "OK", "US", 36.15, -95.99),
    "fresno-ca": ("Fresno", "CA", "US", 36.74, -119.79),
    "worcester-ma": ("Worcester", "MA", "US", 42.26, -71.80),
    "omaha-ne": ("Omaha", "NE", "US", 41.26, -95.93),
    "greenville-sc": ("Greenville", "SC", "US", 34.85, -82.40),
    "albuquerque-nm": ("Albuquerque", "NM", "US", 35.08, -106.65),
    "bakersfield-ca": ("Bakersfield", "CA", "US", 35.37, -119.02),
    "albany-ny": ("Albany", "NY", "US", 42.65, -73.76),
    "knoxville-tn": ("Knoxville", "TN", "US", 35.96, -83.92),
    "elpaso-tx": ("El Paso", "TX", "US", 31.76, -106.49),
    "batonrouge-la": ("Baton Rouge", "LA", "US", 30.45, -91.19),
    "mcallen-tx": ("McAllen", "TX", "US", 26.20, -98.23),
    "allentown-pa": ("Allentown", "PA", "US", 40.60, -75.49),
    "columbia-sc": ("Columbia", "SC", "US", 34.00, -81.03),
    "sarasota-fl": ("Sarasota", "FL", "US", 27.34, -82.53),
    "dayton-oh": ("Dayton", "OH", "US", 39.76, -84.19),
    "charleston-sc": ("Charleston", "SC", "US", 32.78, -79.93),
    "greensboro-nc": ("Greensboro", "NC", "US", 36.07, -79.79),
    "fortmyers-fl": ("Fort Myers", "FL", "US", 26.64, -81.87),
    "boise-id": ("Boise", "ID", "US", 43.62, -116.20),
    "coloradosprings-co": ("Colorado Springs", "CO", "US", 38.83, -104.82),
    "littlerock-ar": ("Little Rock", "AR", "US", 34.75, -92.29),
    "akron-oh": ("Akron", "OH", "US", 41.08, -81.52),
    "desmoines-ia": ("Des Moines", "IA", "US", 41.59, -93.62),
    "syracuse-ny": ("Syracuse", "NY", "US", 43.05, -76.15),
    "madison-wi": ("Madison", "WI", "US", 43.07, -89.40),
    "wichita-ks": ("Wichita", "KS", "US", 37.69, -97.34),
    "harrisburg-pa": ("Harrisburg", "PA", "US", 40.27, -76.88),
    "spokane-wa": ("Spokane", "WA", "US", 47.66, -117.43),
    "toledo-oh": ("Toledo", "OH", "US", 41.65, -83.54),
    "chattanooga-tn": ("Chattanooga", "TN", "US", 35.05, -85.31),
    "jackson-ms": ("Jackson", "MS", "US", 32.30, -90.18),
    "lexington-ky": ("Lexington", "KY", "US", 38.04, -84.50),
    "portland-me": ("Portland", "ME", "US", 43.66, -70.26),
    "reno-nv": ("Reno", "NV", "US", 39.53, -119.81),
    "anchorage-ak": ("Anchorage", "AK", "US", 61.22, -149.90),
    "savannah-ga": ("Savannah", "GA", "US", 32.08, -81.09),
    "corpuschristi-tx": ("Corpus Christi", "TX", "US", 27.80, -97.40),
    "shreveport-la": ("Shreveport", "LA", "US", 32.53, -93.75),
    "mobile-al": ("Mobile", "AL", "US", 30.69, -88.04),
    "huntsville-al": ("Huntsville", "AL", "US", 34.73, -86.59),
    "lubbock-tx": ("Lubbock", "TX", "US", 33.58, -101.86),
    "fayetteville-ar": ("Fayetteville", "AR", "US", 36.06, -94.16),
    "tallahassee-fl": ("Tallahassee", "FL", "US", 30.44, -84.28),
    "montgomery-al": ("Montgomery", "AL", "US", 32.37, -86.30),
    "eugene-or": ("Eugene", "OR", "US", 44.05, -123.09),
    "siouxfalls-sd": ("Sioux Falls", "SD", "US", 43.54, -96.73),
    "fargo-nd": ("Fargo", "ND", "US", 46.88, -96.79),
    "billings-mt": ("Billings", "MT", "US", 45.78, -108.50),
    "burlington-vt": ("Burlington", "VT", "US", 44.48, -73.21),
    "manchester-nh": ("Manchester", "NH", "US", 42.99, -71.46),
    "charleston-wv": ("Charleston", "WV", "US", 38.35, -81.63),
    "roanoke-va": ("Roanoke", "VA", "US", 37.27, -79.94),
    "greenbay-wi": ("Green Bay", "WI", "US", 44.51, -88.02),
    "cedarrapids-ia": ("Cedar Rapids", "IA", "US", 41.98, -91.67),
    "springfield-mo": ("Springfield", "MO", "US", 37.21, -93.29),
    "fortwayne-in": ("Fort Wayne", "IN", "US", 41.08, -85.14),
    "southbend-in": ("South Bend", "IN", "US", 41.68, -86.25),
    "lansing-mi": ("Lansing", "MI", "US", 42.73, -84.56),
    "evansville-in": ("Evansville", "IN", "US", 37.97, -87.57),
    "peoria-il": ("Peoria", "IL", "US", 40.69, -89.59),
    "amarillo-tx": ("Amarillo", "TX", "US", 35.22, -101.83),
    "midland-tx": ("Midland", "TX", "US", 32.00, -102.08),
    "laredo-tx": ("Laredo", "TX", "US", 27.51, -99.51),
    "brownsville-tx": ("Brownsville", "TX", "US", 25.90, -97.50),
    "waco-tx": ("Waco", "TX", "US", 31.55, -97.15),
    "killeen-tx": ("Killeen", "TX", "US", 31.12, -97.73),
    "tyler-tx": ("Tyler", "TX", "US", 32.35, -95.30),
    "beaumont-tx": ("Beaumont", "TX", "US", 30.08, -94.13),
    "palmsprings-ca": ("Palm Springs", "CA", "US", 33.83, -116.55),
    "santabarbara-ca": ("Santa Barbara", "CA", "US", 34.42, -119.70),
    "stockton-ca": ("Stockton", "CA", "US", 37.96, -121.29),
    "modesto-ca": ("Modesto", "CA", "US", 37.64, -120.99),
    "redding-ca": ("Redding", "CA", "US", 40.59, -122.39),
    "monterey-ca": ("Monterey", "CA", "US", 36.60, -121.89),
    "sanluisobispo-ca": ("San Luis Obispo", "CA", "US", 35.28, -120.66),
    "santarosa-ca": ("Santa Rosa", "CA", "US", 38.44, -122.71),
    "medford-or": ("Medford", "OR", "US", 42.33, -122.87),
    "missoula-mt": ("Missoula", "MT", "US", 46.87, -113.99),
    "bozeman-mt": ("Bozeman", "MT", "US", 45.68, -111.04),
    "cheyenne-wy": ("Cheyenne", "WY", "US", 41.14, -104.82),
    "rapidcity-sd": ("Rapid City", "SD", "US", 44.08, -103.23),
    "bismarck-nd": ("Bismarck", "ND", "US", 46.81, -100.78),
    "duluth-mn": ("Duluth", "MN", "US", 46.79, -92.10),
    "fairbanks-ak": ("Fairbanks", "AK", "US", 64.84, -147.72),
    "juneau-ak": ("Juneau", "AK", "US", 58.30, -134.42),
    "kahului-hi": ("Kahului", "HI", "US", 20.89, -156.47),
    "kona-hi": ("Kailua-Kona", "HI", "US", 19.64, -155.99),
    "lihue-hi": ("Lihue", "HI", "US", 21.98, -159.37),
    "hilo-hi": ("Hilo", "HI", "US", 19.72, -155.09),
    "pensacola-fl": ("Pensacola", "FL", "US", 30.42, -87.22),
    "gainesville-fl": ("Gainesville", "FL", "US", 29.65, -82.32),
    "daytonabeach-fl": ("Daytona Beach", "FL", "US", 29.21, -81.02),
    "melbourne-fl": ("Melbourne", "FL", "US", 28.08, -80.61),
    "keywest-fl": ("Key West", "FL", "US", 24.56, -81.78),
    "wilmington-nc": ("Wilmington", "NC", "US", 34.23, -77.94),
    "myrtlebeach-sc": ("Myrtle Beach", "SC", "US", 33.69, -78.89),
    "asheville-nc": ("Asheville", "NC", "US", 35.60, -82.55),
    "winstonsalem-nc": ("Winston-Salem", "NC", "US", 36.10, -80.24),
    "scranton-pa": ("Scranton", "PA", "US", 41.41, -75.66),
    "erie-pa": ("Erie", "PA", "US", 42.13, -80.09),
    "binghamton-ny": ("Binghamton", "NY", "US", 42.10, -75.91),
    "atlanticcity-nj": ("Atlantic City", "NJ", "US", 39.36, -74.42),
    "trenton-nj": ("Trenton", "NJ", "US", 40.22, -74.76),
    "wilmington-de": ("Wilmington", "DE", "US", 39.74, -75.55),
    "whiteplains-ny": ("White Plains", "NY", "US", 41.03, -73.76),
    "islip-ny": ("Islip", "NY", "US", 40.73, -73.21),
    "newburgh-ny": ("Newburgh", "NY", "US", 41.50, -74.01),
    "salisbury-md": ("Salisbury", "MD", "US", 38.36, -75.60),
    "lafayette-la": ("Lafayette", "LA", "US", 30.22, -92.02),
    "gulfport-ms": ("Gulfport", "MS", "US", 30.37, -89.09),
    "augusta-ga": ("Augusta", "GA", "US", 33.47, -81.97),
    "columbus-ga": ("Columbus", "GA", "US", 32.46, -84.99),
    "macon-ga": ("Macon", "GA", "US", 32.84, -83.63),
    "albany-ga": ("Albany", "GA", "US", 31.58, -84.16),
    "valdosta-ga": ("Valdosta", "GA", "US", 30.83, -83.28),
    "dothan-al": ("Dothan", "AL", "US", 31.22, -85.39),
    "charlottesville-va": ("Charlottesville", "VA", "US", 38.03, -78.48),
    "lynchburg-va": ("Lynchburg", "VA", "US", 37.41, -79.14),
    "flint-mi": ("Flint", "MI", "US", 43.01, -83.69),
    "saginaw-mi": ("Saginaw", "MI", "US", 43.42, -83.95),
    "kalamazoo-mi": ("Kalamazoo", "MI", "US", 42.29, -85.59),
    "traversecity-mi": ("Traverse City", "MI", "US", 44.76, -85.62),
    "rockford-il": ("Rockford", "IL", "US", 42.27, -89.09),
    "moline-il": ("Moline", "IL", "US", 41.51, -90.52),
    "champaign-il": ("Champaign", "IL", "US", 40.12, -88.24),
    "springfield-il": ("Springfield", "IL", "US", 39.80, -89.64),
    "topeka-ks": ("Topeka", "KS", "US", 39.05, -95.68),
    "grandjunction-co": ("Grand Junction", "CO", "US", 39.06, -108.55),
    "provo-ut": ("Provo", "UT", "US", 40.23, -111.66),
    "ogden-ut": ("Ogden", "UT", "US", 41.22, -111.97),
    "idahofalls-id": ("Idaho Falls", "ID", "US", 43.49, -112.03),
    "yakima-wa": ("Yakima", "WA", "US", 46.60, -120.51),
    "bellingham-wa": ("Bellingham", "WA", "US", 48.75, -122.48),
    "pasco-wa": ("Pasco", "WA", "US", 46.24, -119.10),
    "bowlinggreen-ky": ("Bowling Green", "KY", "US", 36.99, -86.44),
    # international hubs
    "toronto-on": ("Toronto", "ON", "CA", 43.65, -79.38),
    "montreal-qc": ("Montreal", "QC", "CA", 45.50, -73.57),
    "vancouver-bc": ("Vancouver", "BC", "CA", 49.28, -123.12),
    "calgary-ab": ("Calgary", "AB", "CA", 51.05, -114.07),
    "mexicocity-mx": ("Mexico City", "", "MX", 19.43, -99.13),
    "queretaro-mx": ("Queretaro", "", "MX", 20.59, -100.39),
    "london-gb": ("London", "", "GB", 51.51, -0.13),
    "manchester-gb": ("Manchester", "", "GB", 53.48, -2.24),
    "dublin-ie": ("Dublin", "", "IE", 53.35, -6.26),
    "amsterdam-nl": ("Amsterdam", "", "NL", 52.37, 4.90),
    "brussels-be": ("Brussels", "", "BE", 50.85, 4.35),
    "paris-fr": ("Paris", "", "FR", 48.86, 2.35),
    "marseille-fr": ("Marseille", "", "FR", 43.30, 5.37),
    "frankfurt-de": ("Frankfurt", "", "DE", 50.11, 8.68),
    "hamburg-de": ("Hamburg", "", "DE", 53.55, 9.99),
    "munich-de": ("Munich", "", "DE", 48.14, 11.58),
    "dusseldorf-de": ("Dusseldorf", "", "DE", 51.23, 6.77),
    "zurich-ch": ("Zurich", "", "CH", 47.38, 8.54),
    "vienna-at": ("Vienna", "", "AT", 48.21, 16.37),
    "milan-it": ("Milan", "", "IT", 45.46, 9.19),
    "rome-it": ("Rome", "", "IT", 41.90, 12.50),
    "madrid-es": ("Madrid", "", "ES", 40.42, -3.70),
    "barcelona-es": ("Barcelona", "", "ES", 41.39, 2.17),
    "lisbon-pt": ("Lisbon", "", "PT", 38.72, -9.14),
    "stockholm-se": ("Stockholm", "", "SE", 59.33, 18.07),
    "copenhagen-dk": ("Copenhagen", "", "DK", 55.68, 12.57),
    "oslo-no": ("Oslo", "", "NO", 59.91, 10.75),
    "helsinki-fi": ("Helsinki", "", "FI", 60.17, 24.94),
    "warsaw-pl": ("Warsaw", "", "PL", 52.23, 21.01),
    "prague-cz": ("Prague", "", "CZ", 50.08, 14.44),
    "budapest-hu": ("Budapest", "", "HU", 47.50, 19.04),
    "bucharest-ro": ("Bucharest", "", "RO", 44.43, 26.10),
    "sofia-bg": ("Sofia", "", "BG", 42.70, 23.32),
    "bratislava-sk": ("Bratislava", "", "SK", 48.15, 17.11),
    "kyiv-ua": ("Kyiv", "", "UA", 50.45, 30.52),
    "moscow-ru": ("Moscow", "", "RU", 55.76, 37.62),
    "istanbul-tr": ("Istanbul", "", "TR", 41.01, 28.98),
    "dubai-ae": ("Dubai", "", "AE", 25.20, 55.27),
    "mumbai-in": ("Mumbai", "", "IN", 19.08, 72.88),
    "chennai-in": ("Chennai", "", "IN", 13.08, 80.27),
    "singapore-sg": ("Singapore", "", "SG", 1.35, 103.82),
    "kualalumpur-my": ("Kuala Lumpur", "", "MY", 3.14, 101.69),
    "jakarta-id": ("Jakarta", "", "ID", -6.21, 106.85),
    "hongkong-hk": ("Hong Kong", "", "HK", 22.32, 114.17),
    "taipei-tw": ("Taipei", "", "TW", 25.03, 121.57),
    "tokyo-jp": ("Tokyo", "", "JP", 35.68, 139.69),
    "osaka-jp": ("Osaka", "", "JP", 34.69, 135.50),
    "seoul-kr": ("Seoul", "", "KR", 37.57, 126.98),
    "sydney-au": ("Sydney", "", "AU", -33.87, 151.21),
    "johannesburg-za": ("Johannesburg", "", "ZA", -26.20, 28.05),
    "saopaulo-br": ("Sao Paulo", "", "BR", -23.55, -46.63),
}

# 3-letter code -> (metro key, usable for unknown domains). False: a word or common token, a country short
# form (aus, ind), a metro-area code or a foreign airport, read by carrier rules only
IATA: Dict[str, Tuple[str, bool]] = {
    # US airports (the city served; OurAirports "municipality" can differ, e.g. CVG is in Hebron KY)
    "jfk": ("newyork-ny", True),
    "lga": ("newyork-ny", True),
    "ewr": ("newark-nj", True),
    "lax": ("losangeles-ca", True),
    "lgb": ("longbeach-ca", True),
    "sna": ("santaana-ca", True),
    "bur": ("burbank-ca", True),
    "ont": ("ontario-ca", False),
    "ord": ("chicago-il", True),
    "mdw": ("chicago-il", True),
    "dfw": ("dallas-tx", True),
    "dal": ("dallas-tx", False),
    "iah": ("houston-tx", True),
    "hou": ("houston-tx", True),
    "dca": ("washington-dc", True),
    "iad": ("ashburn-va", True),
    "bwi": ("baltimore-md", True),
    "phl": ("philadelphia-pa", True),
    "mia": ("miami-fl", True),
    "fll": ("fortlauderdale-fl", True),
    "pbi": ("westpalmbeach-fl", True),
    "atl": ("atlanta-ga", True),
    "bos": ("boston-ma", True),
    "phx": ("phoenix-az", True),
    "sfo": ("sanfrancisco-ca", True),
    "oak": ("oakland-ca", True),
    "sjc": ("sanjose-ca", True),
    "pao": ("paloalto-ca", False),
    "dtw": ("detroit-mi", True),
    "sea": ("seattle-wa", True),
    "msp": ("minneapolis-mn", True),
    "san": ("sandiego-ca", False),
    "tpa": ("tampa-fl", True),
    "den": ("denver-co", True),
    "stl": ("stlouis-mo", True),
    "mco": ("orlando-fl", True),
    "clt": ("charlotte-nc", True),
    "sat": ("sanantonio-tx", False),
    "pdx": ("portland-or", True),
    "smf": ("sacramento-ca", True),
    "pit": ("pittsburgh-pa", True),
    "aus": ("austin-tx", False),
    "las": ("lasvegas-nv", True),
    "cvg": ("cincinnati-oh", True),
    "cmh": ("columbus-oh", True),
    "ind": ("indianapolis-in", False),
    "cle": ("cleveland-oh", True),
    "bna": ("nashville-tn", True),
    "orf": ("norfolk-va", True),
    "phf": ("newportnews-va", True),
    "pvd": ("providence-ri", True),
    "jax": ("jacksonville-fl", True),
    "mke": ("milwaukee-wi", True),
    "rdu": ("raleigh-nc", True),
    "okc": ("oklahomacity-ok", True),
    "mem": ("memphis-tn", False),
    "ric": ("richmond-va", True),
    "sdf": ("louisville-ky", True),
    "msy": ("neworleans-la", True),
    "slc": ("saltlakecity-ut", True),
    "bdl": ("hartford-ct", True),
    "hvn": ("newhaven-ct", True),
    "buf": ("buffalo-ny", False),
    "bhm": ("birmingham-al", True),
    "roc": ("rochester-ny", True),
    "grr": ("grandrapids-mi", True),
    "tus": ("tucson-az", True),
    "hnl": ("honolulu-hi", True),
    "tul": ("tulsa-ok", True),
    "fat": ("fresno-ca", False),
    "orh": ("worcester-ma", True),
    "oma": ("omaha-ne", True),
    "gsp": ("greenville-sc", True),
    "abq": ("albuquerque-nm", True),
    "bfl": ("bakersfield-ca", True),
    "alb": ("albany-ny", False),
    "tys": ("knoxville-tn", True),
    "elp": ("elpaso-tx", True),
    "btr": ("batonrouge-la", True),
    "mfe": ("mcallen-tx", True),
    "abe": ("allentown-pa", True),
    "cae": ("columbia-sc", True),
    "srq": ("sarasota-fl", True),
    "day": ("dayton-oh", False),
    "chs": ("charleston-sc", True),
    "gso": ("greensboro-nc", True),
    "rsw": ("fortmyers-fl", True),
    "boi": ("boise-id", True),
    "cos": ("coloradosprings-co", False),
    "lit": ("littlerock-ar", False),
    "cak": ("akron-oh", True),
    "dsm": ("desmoines-ia", True),
    "syr": ("syracuse-ny", True),
    "msn": ("madison-wi", False),
    "ict": ("wichita-ks", True),
    "mdt": ("harrisburg-pa", True),
    "geg": ("spokane-wa", True),
    "tol": ("toledo-oh", True),
    "cha": ("chattanooga-tn", False),
    "jan": ("jackson-ms", False),
    "lex": ("lexington-ky", True),
    "pwm": ("portland-me", True),
    "rno": ("reno-nv", True),
    "anc": ("anchorage-ak", True),
    "sav": ("savannah-ga", False),
    "crp": ("corpuschristi-tx", True),
    "shv": ("shreveport-la", True),
    "mob": ("mobile-al", False),
    "hsv": ("huntsville-al", True),
    "lbb": ("lubbock-tx", True),
    "xna": ("fayetteville-ar", True),
    "tlh": ("tallahassee-fl", True),
    "mgm": ("montgomery-al", True),
    "eug": ("eugene-or", True),
    "fsd": ("siouxfalls-sd", True),
    "far": ("fargo-nd", False),
    "bil": ("billings-mt", True),
    "btv": ("burlington-vt", True),
    "mht": ("manchester-nh", True),
    "crw": ("charleston-wv", True),
    "roa": ("roanoke-va", True),
    "grb": ("greenbay-wi", True),
    "cid": ("cedarrapids-ia", False),
    "sgf": ("springfield-mo", True),
    "fwa": ("fortwayne-in", False),
    "sbn": ("southbend-in", True),
    "lan": ("lansing-mi", False),
    "evv": ("evansville-in", True),
    "pia": ("peoria-il", True),
    "ama": ("amarillo-tx", True),
    "maf": ("midland-tx", True),
    "lrd": ("laredo-tx", True),
    "bro": ("brownsville-tx", True),
    "act": ("waco-tx", False),
    "grk": ("killeen-tx", True),
    "tyr": ("tyler-tx", True),
    "bpt": ("beaumont-tx", False),
    "psp": ("palmsprings-ca", True),
    "sba": ("santabarbara-ca", True),
    "sck": ("stockton-ca", True),
    "mod": ("modesto-ca", False),
    "rdd": ("redding-ca", True),
    "mry": ("monterey-ca", True),
    "sbp": ("sanluisobispo-ca", True),
    "sts": ("santarosa-ca", True),
    "mfr": ("medford-or", True),
    "mso": ("missoula-mt", True),
    "bzn": ("bozeman-mt", True),
    "cys": ("cheyenne-wy", True),
    "rap": ("rapidcity-sd", False),
    "bis": ("bismarck-nd", False),
    "dlh": ("duluth-mn", True),
    "fai": ("fairbanks-ak", True),
    "jnu": ("juneau-ak", True),
    "ogg": ("kahului-hi", True),
    "koa": ("kona-hi", True),
    "lih": ("lihue-hi", True),
    "ito": ("hilo-hi", False),
    "pns": ("pensacola-fl", True),
    "gnv": ("gainesville-fl", True),
    "dab": ("daytonabeach-fl", True),
    "mlb": ("melbourne-fl", True),
    "eyw": ("keywest-fl", True),
    "ilm": ("wilmington-nc", True),
    "myr": ("myrtlebeach-sc", True),
    "avl": ("asheville-nc", True),
    "int": ("winstonsalem-nc", False),
    "avp": ("scranton-pa", False),
    "eri": ("erie-pa", True),
    "bgm": ("binghamton-ny", True),
    "acy": ("atlanticcity-nj", True),
    "ttn": ("trenton-nj", True),
    "ilg": ("wilmington-de", True),
    "hpn": ("whiteplains-ny", True),
    "isp": ("islip-ny", False),
    "swf": ("newburgh-ny", True),
    "sby": ("salisbury-md", True),
    "lft": ("lafayette-la", True),
    "gpt": ("gulfport-ms", False),
    "ags": ("augusta-ga", True),
    "csg": ("columbus-ga", True),
    "mcn": ("macon-ga", True),
    "aby": ("albany-ga", True),
    "vld": ("valdosta-ga", True),
    "dhn": ("dothan-al", True),
    "cho": ("charlottesville-va", True),
    "lyh": ("lynchburg-va", True),
    "fnt": ("flint-mi", True),
    "mbs": ("saginaw-mi", True),
    "azo": ("kalamazoo-mi", True),
    "tvc": ("traversecity-mi", True),
    "rfd": ("rockford-il", True),
    "mli": ("moline-il", True),
    "cmi": ("champaign-il", True),
    "spi": ("springfield-il", True),
    "foe": ("topeka-ks", True),
    "gjt": ("grandjunction-co", True),
    "pvu": ("provo-ut", True),
    "ogd": ("ogden-ut", True),
    "ida": ("idahofalls-id", True),
    "ykm": ("yakima-wa", True),
    "bli": ("bellingham-wa", True),
    "psc": ("pasco-wa", True),
    "bwg": ("bowlinggreen-ky", True),
    # IATA metropolitan-area codes (not airports; absent from OurAirports): carrier rules only
    "nyc": ("newyork-ny", False),
    "chi": ("chicago-il", False),
    "was": ("washington-dc", False),
    "yto": ("toronto-on", False),
    "ymq": ("montreal-qc", False),
    "lon": ("london-gb", False),
    "par": ("paris-fr", False),
    "mil": ("milan-it", False),
    "sto": ("stockholm-se", False),
    "mow": ("moscow-ru", False),
    "tyo": ("tokyo-jp", False),
    "osa": ("osaka-jp", False),
    "sel": ("seoul-kr", False),
    "sao": ("saopaulo-br", False),
    "buh": ("bucharest-ro", False),
    "jkt": ("jakarta-id", False),
    "rom": ("rome-it", False),
    # international airports: carrier rules only
    "yyz": ("toronto-on", False),
    "yul": ("montreal-qc", False),
    "yvr": ("vancouver-bc", False),
    "yyc": ("calgary-ab", False),
    "mex": ("mexicocity-mx", False),
    "qro": ("queretaro-mx", False),
    "lhr": ("london-gb", False),
    "lcy": ("london-gb", False),
    "man": ("manchester-gb", False),
    "dub": ("dublin-ie", False),
    "ams": ("amsterdam-nl", False),
    "bru": ("brussels-be", False),
    "cdg": ("paris-fr", False),
    "mrs": ("marseille-fr", False),
    "fra": ("frankfurt-de", False),
    "ham": ("hamburg-de", False),
    "muc": ("munich-de", False),
    "dus": ("dusseldorf-de", False),
    "zrh": ("zurich-ch", False),
    "vie": ("vienna-at", False),
    "mxp": ("milan-it", False),
    "fco": ("rome-it", False),
    "mad": ("madrid-es", False),
    "bcn": ("barcelona-es", False),
    "lis": ("lisbon-pt", False),
    "arn": ("stockholm-se", False),
    "cph": ("copenhagen-dk", False),
    "osl": ("oslo-no", False),
    "hel": ("helsinki-fi", False),
    "waw": ("warsaw-pl", False),
    "prg": ("prague-cz", False),
    "bud": ("budapest-hu", False),
    "otp": ("bucharest-ro", False),
    "sof": ("sofia-bg", False),
    "bts": ("bratislava-sk", False),
    "kbp": ("kyiv-ua", False),
    "svo": ("moscow-ru", False),
    "ist": ("istanbul-tr", False),
    "dxb": ("dubai-ae", False),
    "bom": ("mumbai-in", False),
    "maa": ("chennai-in", False),
    "sin": ("singapore-sg", False),
    "kul": ("kualalumpur-my", False),
    "cgk": ("jakarta-id", False),
    "hkg": ("hongkong-hk", False),
    "tpe": ("taipei-tw", False),
    "nrt": ("tokyo-jp", False),
    "hnd": ("tokyo-jp", False),
    "kix": ("osaka-jp", False),
    "icn": ("seoul-kr", False),
    "syd": ("sydney-au", False),
    "jnb": ("johannesburg-za", False),
    "gru": ("saopaulo-br", False),
}

# 6-letter place code (4 letters for the place, 2 for the state or country) -> metro key; each one seen in a
# public router name
CLLI: Dict[str, str] = {
    "nycmny": "newyork-ny",
    "chcgil": "chicago-il",
    "dllstx": "dallas-tx",
    "lsanca": "losangeles-ca",
    "atlnga": "atlanta-ga",
    "asbnva": "ashburn-va",
    "snjsca": "sanjose-ca",
    "sttlwa": "seattle-wa",
    "miamfl": "miami-fl",
    "bstnma": "boston-ma",
    "nwrknj": "newark-nj",
    "plalca": "paloalto-ca",
    "scrmca": "sacramento-ca",
    "washdc": "washington-dc",
    "bltmmd": "baltimore-md",
    "hstntx": "houston-tx",
    "irvnca": "irvine-ca",
    "rcsntx": "richardson-tx",
    "drhmnc": "durham-nc",
    "bwlgky": "bowlinggreen-ky",
    "stlsmo": "stlouis-mo",
    "jcvlfl": "jacksonville-fl",
    "albqnm": "albuquerque-nm",
    "ftwyin": "fortwayne-in",
    "lnbhca": "longbeach-ca",
    "chtnwv": "charleston-wv",
    "snfcca": "sanfrancisco-ca",
    "iplsin": "indianapolis-in",
    "amstnl": "amsterdam-nl",
    "frnkge": "frankfurt-de",
    "londen": "london-gb",
    "parsfr": "paris-fr",
    "tokyjp": "tokyo-jp",
    "sngpsi": "singapore-sg",
    "vienat": "vienna-at",
    "mdrdsp": "madrid-es",
    "stocse": "stockholm-se",
    "sydnau": "sydney-au",
    "toroon": "toronto-on",
    "osakjp": "osaka-jp",
    "seolko": "seoul-kr",
    "taiptw": "taipei-tw",
    "saplbr": "saopaulo-br",
    "budahu": "budapest-hu",
    "buchro": "bucharest-ro",
    "barcsp": "barcelona-es",
    "mrslfr": "marseille-fr",
}

# compact city name -> ((metro key, generic), ...). Several rows make an ambiguous name (every row generic=False):
# it needs a state label or a carrier override. The first row is the usual meaning.
CITY: Dict[str, Tuple[Tuple[str, bool], ...]] = {
    "newyork": (("newyork-ny", True),),
    "losangeles": (("losangeles-ca", True),),
    "chicago": (("chicago-il", True),),
    "dallas": (("dallas-tx", True),),
    "houston": (("houston-tx", True),),
    "washington": (("washington-dc", False),),
    "ashburn": (("ashburn-va", True),),
    "reston": (("reston-va", True),),
    "herndon": (("herndon-va", True),),
    "philadelphia": (("philadelphia-pa", True),),
    "miami": (("miami-fl", True),),
    "atlanta": (("atlanta-ga", True),),
    "boston": (("boston-ma", True),),
    "phoenix": (("phoenix-az", False),),
    "sanfrancisco": (("sanfrancisco-ca", True),),
    "oakland": (("oakland-ca", True),),
    "sanjose": (("sanjose-ca", True),),
    "santaclara": (("santaclara-ca", True),),
    "sunnyvale": (("sunnyvale-ca", True),),
    "paloalto": (("paloalto-ca", True),),
    "fremont": (("fremont-ca", False),),
    "tustin": (("tustin-ca", True),),
    "irvine": (("irvine-ca", True),),
    "anaheim": (("anaheim-ca", True),),
    "detroit": (("detroit-mi", True),),
    "seattle": (("seattle-wa", True),),
    "minneapolis": (("minneapolis-mn", True),),
    "sandiego": (("sandiego-ca", True),),
    "tampa": (("tampa-fl", True),),
    "denver": (("denver-co", True),),
    "stlouis": (("stlouis-mo", True),),
    "saintlouis": (("stlouis-mo", True),),
    "baltimore": (("baltimore-md", True),),
    "orlando": (("orlando-fl", True),),
    "charlotte": (("charlotte-nc", True),),
    "sanantonio": (("sanantonio-tx", True),),
    "portland": (("portland-or", False), ("portland-me", False)),
    "sacramento": (("sacramento-ca", True),),
    "pittsburgh": (("pittsburgh-pa", True),),
    "austin": (("austin-tx", True),),
    "lasvegas": (("lasvegas-nv", True),),
    "cincinnati": (("cincinnati-oh", True),),
    "columbus": (("columbus-oh", False), ("columbus-ga", False)),
    "indianapolis": (("indianapolis-in", True),),
    "cleveland": (("cleveland-oh", True),),
    "nashville": (("nashville-tn", True),),
    "jacksonville": (("jacksonville-fl", False),),
    "milwaukee": (("milwaukee-wi", True),),
    "raleigh": (("raleigh-nc", True),),
    "oklahomacity": (("oklahomacity-ok", True),),
    "memphis": (("memphis-tn", True),),
    "richmond": (("richmond-va", False),),
    "louisville": (("louisville-ky", True),),
    "neworleans": (("neworleans-la", True),),
    "saltlakecity": (("saltlakecity-ut", True),),
    "albuquerque": (("albuquerque-nm", True),),
    "tucson": (("tucson-az", True),),
    "honolulu": (("honolulu-hi", True),),
    "tulsa": (("tulsa-ok", True),),
    "omaha": (("omaha-ne", True),),
    "elpaso": (("elpaso-tx", True),),
    "desmoines": (("desmoines-ia", True),),
    "anchorage": (("anchorage-ak", True),),
    "newark": (("newark-nj", False),),
    "secaucus": (("secaucus-nj", True),),
    "fortworth": (("fortworth-tx", True),),
    "richardson": (("richardson-tx", True),),
    "buffalo": (("buffalo-ny", False),),
    "birmingham": (("birmingham-al", False),),
    "charleston": (("charleston-sc", False), ("charleston-wv", False)),
    "springfield": (("springfield-mo", False), ("springfield-il", False)),
    "wilmington": (("wilmington-de", False), ("wilmington-nc", False)),
    "albany": (("albany-ny", False), ("albany-ga", False)),
    "manchester": (("manchester-nh", False), ("manchester-gb", False)),
    "mobile": (("mobile-al", False),),
    "london": (("london-gb", False),),
    "amsterdam": (("amsterdam-nl", False),),
    "frankfurt": (("frankfurt-de", True),),
    "paris": (("paris-fr", False),),
    "madrid": (("madrid-es", True),),
    "milan": (("milan-it", True),),
    "zurich": (("zurich-ch", True),),
    "vienna": (("vienna-at", False),),
    "stockholm": (("stockholm-se", True),),
    "copenhagen": (("copenhagen-dk", True),),
    "hongkong": (("hongkong-hk", True),),
    "singapore": (("singapore-sg", True),),
    "tokyo": (("tokyo-jp", True),),
    "sydney": (("sydney-au", True),),
    "saopaulo": (("saopaulo-br", True),),
    "toronto": (("toronto-on", True),),
    "montreal": (("montreal-qc", True),),
    "vancouver": (("vancouver-bc", False),),
    "istanbul": (("istanbul-tr", True),),
    "taipei": (("taipei-tw", True),),
    "dublin": (("dublin-ie", False),),
    "marseille": (("marseille-fr", True),),
    "hamburg": (("hamburg-de", True),),
    "munich": (("munich-de", True),),
    "warsaw": (("warsaw-pl", True),),
    "prague": (("prague-cz", True),),
    "budapest": (("budapest-hu", True),),
    "johannesburg": (("johannesburg-za", True),),
    "mumbai": (("mumbai-in", True),),
    "seoul": (("seoul-kr", True),),
    "osaka": (("osaka-jp", True),),
}

# digit-led street or facility token -> metro key (the digits belong to the token: "56marietta" is Atlanta)
FACILITY: Dict[str, str] = {
    "350ecermak": "chicago-il",
    "111eighthave": "newyork-ny",
    "56marietta": "atlanta-ga",
}

# override set -> the carrier's own code -> metro key. An "override" rule never falls back to a dictionary;
# the other rule kinds try their set first.
OVERRIDES: Dict[str, Dict[str, str]] = {
    # Hurricane Electric (AS6939)
    "he": {
        "ash": "ashburn-va",
        "fmt": "fremont-ca",
        "chi": "chicago-il",
        "nyc": "newyork-ny",
        "tor": "toronto-on",
        "ymq": "montreal-qc",
        "lon": "london-gb",
        "par": "paris-fr",
        "pao": "paloalto-ca",
        "dal": "dallas-tx",
    },
    # GTT (AS3257)
    "gtt": {
        "chi": "chicago-il",
        "nyc": "newyork-ny",
        "dal": "dallas-tx",
        "tor": "toronto-on",
        "mtl": "montreal-qc",
        "zur": "zurich-ch",
        "lon": "london-gb",
        "par": "paris-fr",
    },
    # Zayo (AS6461)
    "zayo": {
        "tor": "toronto-on",
    },
    # Cogent (AS174)
    "cogent": {
        "lon": "london-gb",
    },
    # Verizon Business (AS701)
    "alter": {
        "chi": "chicago-il",
        "nyc": "newyork-ny",
    },
    # NTT (AS2914) - NTT-made place codes
    "ntt": {
        "mlanit": "milan-it",
    },
    # Arelion / Telia Carrier (AS1299) - own codes; NEVER fall back to the IATA dictionary
    "arelion": {
        "nyk": "newyork-ny",
        "chi": "chicago-il",
        "lax": "losangeles-ca",
        "prs": "paris-fr",
        "adm": "amsterdam-nl",
        "ldn": "london-gb",
        "ffm": "frankfurt-de",
        "ash": "ashburn-va",
        "zch": "zurich-ch",
        "mad": "madrid-es",
        "mow": "moscow-ru",
        "bpt": "budapest-hu",  # collision: Arelion's own Budapest code; IATA BPT is Beaumont, TX
        "rom": "rome-it",
        "den": "denver-co",
    },
    # Lumen legacy Qwest (AS209) - own 3-letter codes, several collide with foreign airports
    "qwest": {
        "abq": "albuquerque-nm",
        "atl": "atlanta-ga",
        "dal": "dallas-tx",
        "sea": "seattle-wa",
        "lsv": "lasvegas-nv",
        "jfk": "newyork-ny",
        "los": "losangeles-ca",
        "dca": "washington-dc",
        "chc": "chicago-il",
        "phx": "phoenix-az",
        "dvr": "denver-co",
        "min": "minneapolis-mn",
        "tpa": "tampa-fl",
        "por": "portland-or",
        "slc": "saltlakecity-ut",
    },
    # AT&T backbone (AS7018) - 5-char codes, last two = state
    "att": {
        "dlstx": "dallas-tx",
        "cgcil": "chicago-il",
        "n54ny": "newyork-ny",
        "attga": "atlanta-ga",
        "dvmco": "denver-co",
        "slkut": "saltlakecity-ut",
        "la2ca": "losangeles-ca",
        "sffca": "sanfrancisco-ca",
        "wswdc": "washington-dc",
        "sl9mo": "stlouis-mo",
        "phmaz": "phoenix-az",
        "sd2ca": "sandiego-ca",
        "st6wa": "seattle-wa",
    },
    # Cox (AS22773) backbone 4-letter prefixes
    "cox": {
        "sanj": "sanjose-ca",
        "ashb": "ashburn-va",
        "chgo": "chicago-il",
    },
    # Lumen / Level 3 (AS3356) city-name defaults for ambiguous names
    "level3": {
        "washington": "washington-dc",
        "manchesteruk": "manchester-gb",
        "london": "london-gb",
        "amsterdam": "amsterdam-nl",
    },
    # Tata (AS6453) city-name defaults
    "tata": {
        "amsterdam": "amsterdam-nl",
        "london": "london-gb",
    },
}

# (domain suffix, kind, override set or "-", regex on the lower-cased name without its trailing dot), in table
# order. The longest matching suffix picks its rows: its customer rows are checked first, then the others in
# order (the first match wins).
RULES: Tuple[Tuple[str, str, str, str], ...] = (
    ("rr.com", "customer", "-", r"\.(?:res|biz)\.rr\.com$"),
    ("spectrum.com", "customer", "-", r"\.(?:res|biz)\.spectrum\.com$"),
    ("verizon.net", "customer", "-", r"\.fios\.verizon\.net$"),
    ("sbcglobal.net", "customer", "-", r"."),
    ("att.net", "customer", "-", r"\.dsl\.att\.net$"),
    ("ip.att.net", "override", "att", r"^[^.]+\.(?P<code>[a-z0-9]{3}[a-z]{2})\.ip\.att\.net$"),
    ("level3.net", "city", "level3", r"\.(?P<code>[a-z]+)\d+\.level3\.net$"),
    ("lumen.tech", "city", "level3", r"\.(?P<code>[a-z]+)\d+\.net\.lumen\.tech$"),
    ("cogentco.com", "iata", "cogent", r"\.(?P<code>[a-z]{3})\d{2}\.atlas\.cogentco\.com$"),
    ("he.net", "iata", "he", r"\.(?P<code>[a-z]{3})\d+\.he\.net$"),
    ("zayo.com", "iata_cc", "zayo", r"\.(?P<code>[a-z]{3})\d+\.(?P<cc>[a-z]{2})\.(?:zip|eth)\.zayo\.com$"),
    ("gtt.net", "iata", "gtt", r"[.-](?P<code>[a-z]{3})\d+(?:[a-z]?-e\d+)?\.ip[46]\.gtt\.net$"),
    ("ntt.net", "clli_cc", "ntt", r"\.(?P<code>[a-z]{6})\d+\.(?P<cc>[a-z]{2})\.(?:bb|ce)\.gin\.ntt\.net$"),
    ("twelve99.net", "override", "arelion", r"^(?P<code>[a-z]{1,4})-[a-z0-9]+-link\.(?:ip\.)?twelve99\.net$"),
    ("telia.net", "override", "arelion", r"^(?P<code>[a-z]{1,4})-[a-z]{1,2}\d+-link\.telia\.net$"),
    ("as6453.net", "city", "tata", r"\.[a-z0-9]{2,5}-(?P<code>[a-z]+)\.as6453\.net$"),
    ("alter.net", "iata", "alter", r"\.(?P<code>[a-z]{3})\d+\.alter\.net$"),
    ("verizon-gni.net", "clli", "-", r"^[^.]+\.(?P<code>[a-z]{6})-[a-z]{2,4}-\d+\.verizon-gni\.net$"),
    ("verizon-gni.net", "iata", "-", r"^[^.]+\.(?P<code>[a-z]{3})\d{2}-bb-rtr\d+\.verizon-gni\.net$"),
    ("tbone.rr.com", "clli", "-", r"^[^.]+\.(?P<code>[a-z]{6})[a-z0-9]{3,6}-[a-z]{3}\d{2}\.tbone\.rr\.com$"),
    ("netops.charter.com", "clli", "-", r"^[^.]+\.(?P<code>[a-z]{6})[a-z0-9]{3,6}\.netops\.charter\.com$"),
    ("qwest.net", "override", "qwest", r"^(?P<code>[a-z]{3})\d*-(?:edge|core|cntr|agw|brdr)[-0-9]*\.inet\.qwest\.net$"),
    ("cox.net", "override", "cox", r"^(?P<code>[a-z]{4})[a-z]{4}\d{2}-[^.]+\.[^.]+\.rd\.[a-z]{2}\.cox\.net$"),
    ("cox.net", "iata_st", "-", r"\.(?P<code>[a-z]{3})\.(?P<st>[a-z]{2})\.cox\.net$"),
    ("windstream.net", "clli4_st", "-", r"\.(?P<code>[a-z]{4})\d{2}-(?P<st>[a-z]{2})\.us\.windstream\.net$"),
    ("frontiernet.net", "clli4_st", "-", r"\.(?P<code>[a-z]{4})\.(?P<st>[a-z]{2})\.frontiernet\.net$"),
    ("1e100.net", "iata", "-", r"^(?P<code>[a-z]{3})\d{2}s\d{2,3}-in-[fx]\d+\.1e100\.net$"),
)

# country token used in host names -> ISO 3166 alpha-2
CC_TOKENS: Dict[str, str] = {"uk": "GB", "gb": "GB", "us": "US"}

# US state label -> name (including dc and pr)
US_STATES: Dict[str, str] = {
    "al": "Alabama", "ak": "Alaska", "az": "Arizona", "ar": "Arkansas", "ca": "California", "co": "Colorado",
    "ct": "Connecticut", "de": "Delaware", "dc": "District of Columbia", "fl": "Florida", "ga": "Georgia",
    "hi": "Hawaii", "id": "Idaho", "il": "Illinois", "in": "Indiana", "ia": "Iowa", "ks": "Kansas", "ky": "Kentucky",
    "la": "Louisiana", "me": "Maine", "md": "Maryland", "ma": "Massachusetts", "mi": "Michigan", "mn": "Minnesota",
    "ms": "Mississippi", "mo": "Missouri", "mt": "Montana", "ne": "Nebraska", "nv": "Nevada", "nh": "New Hampshire",
    "nj": "New Jersey", "nm": "New Mexico", "ny": "New York", "nc": "North Carolina", "nd": "North Dakota",
    "oh": "Ohio", "ok": "Oklahoma", "or": "Oregon", "pa": "Pennsylvania", "ri": "Rhode Island",
    "sc": "South Carolina", "sd": "South Dakota", "tn": "Tennessee", "tx": "Texas", "ut": "Utah", "vt": "Vermont",
    "va": "Virginia", "wa": "Washington", "wv": "West Virginia", "wi": "Wisconsin", "wy": "Wyoming",
    "pr": "Puerto Rico",
}

# tokens the generic tier never reads as a place
# interface / role / protocol words (several are also IATA codes: gig=Rio GIG, eth=Eilat ETH, cpe=Campeche CPE,
# ext=Exeter EXT, cor=Cordoba COR, bar, can=Guangzhou CAN, san, ont, isp, lan, int, act, cos, fat, day ...)
STOP: FrozenSet[str] = frozenset({
    "ae", "xe", "ge", "et", "te", "be", "bu", "hu", "po", "so", "gi", "fa", "lo", "lag", "vlan", "vl", "irb",
    "bundle", "ether", "eth", "gig", "gige", "tengig", "tge", "hge", "fortygige", "hundredgige", "core", "cor",
    "edge", "ear", "bar", "bear", "ebr", "car", "csw", "lar", "agr", "agg", "aggr", "acc", "access", "dist", "bdr",
    "border", "peer", "peering", "transit", "ix", "cix", "nap", "cr", "ccr", "rcr", "mpr", "mcs", "er", "sr", "br",
    "ar", "gw", "gwr", "bb", "bcr", "lcr", "pe", "rtr", "router", "switch", "sw", "link", "int", "ext", "mgmt",
    "loop", "loopback", "ipv4", "ipv6", "ip4", "ip6", "net", "inet", "gin", "atlas", "zip", "ibone", "tbone",
    "netops", "rd", "dsl", "pool", "static", "dynamic", "dyn", "dhcp", "ppp", "cust", "customer", "res", "biz", "hsd",
    "hfc", "cable", "fiber", "fios", "lightspeed", "cpe", "host", "server", "srv", "vps", "vm", "cloud", "nat", "cgn",
    "bras", "bng", "olt", "dslam", "cmts", "ubr", "cbr", "jun", "cisco", "nokia", "juniper", "arista", "san", "ont",
    "isp", "lan", "wan", "man", "dmz", "vip", "dev", "lab", "test", "prod", "pub", "prv", "www", "mail", "smtp", "mx",
    "ns", "dns", "voip", "sip", "pbx", "vpn", "fw", "lb", "can", "act", "cos", "fat", "day", "mem", "mob", "alb",
    "buf", "far", "cid", "fwa", "avp", "gpt", "bis", "rap", "ito", "sav", "cha", "jan", "lit", "msn", "mod",
})

# every country code in METROS -> DB-IP Lite's English country name (read from the 2026-09 city file)
COUNTRY_NAMES: Dict[str, str] = {
    "AE": "United Arab Emirates", "AT": "Austria", "AU": "Australia", "BE": "Belgium", "BG": "Bulgaria",
    "BR": "Brazil", "CA": "Canada", "CH": "Switzerland", "CZ": "Czechia", "DE": "Germany", "DK": "Denmark",
    "ES": "Spain", "FI": "Finland", "FR": "France", "GB": "United Kingdom", "HK": "Hong Kong", "HU": "Hungary",
    "ID": "Indonesia", "IE": "Ireland", "IN": "India", "IT": "Italy", "JP": "Japan", "KR": "South Korea",
    "MX": "Mexico", "MY": "Malaysia", "NL": "The Netherlands", "NO": "Norway", "PL": "Poland", "PT": "Portugal",
    "RO": "Romania", "RU": "Russia", "SE": "Sweden", "SG": "Singapore", "SK": "Slovakia", "TR": "Turkey",
    "TW": "Taiwan", "UA": "Ukraine", "US": "United States", "ZA": "South Africa",
}
